/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(qs1r_src.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(01c5e62d62a3e938c7e94673689eb860)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/qs1r/qs1r_src.h>
// pydoc.h is automatically generated in the build directory
#include <qs1r_src_pydoc.h>

void bind_qs1r_src(py::module& m)
{

    using qs1r_src = ::gr::qs1r::qs1r_src;


    py::class_<qs1r_src,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<qs1r_src>>(m, "qs1r_src", D(qs1r_src))

        .def(py::init(&qs1r_src::make),
             py::arg("frequency"),
             py::arg("samplerate"),
             py::arg("pga_flag"),
             py::arg("rand_flag"),
             py::arg("dith_flag"),
             py::arg("ppm"),
             D(qs1r_src, make))


        ;
}
