/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-qs1r
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_QS1R_API_H
#define INCLUDED_QS1R_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_qs1r_EXPORTS
#define QS1R_API __GR_ATTR_EXPORT
#else
#define QS1R_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_QS1R_API_H */
